name: Worker Pool tests

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: golang:1.24.3-alpine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: go test -v -count=1 ./internal/worker_pull/